import { NextResponse } from "next/server";
import type { NextRequest } from "next/server";
import { locales, defaultLocale, hasLocale } from "@/lib/i18n";
import { COOKIE_NAME, verifyToken, verifyCookie, cookieValue } from "@/lib/auth";

// Paths that are accessible without a valid auth cookie.
const PUBLIC_PATHS = ["/unauthorized"];

function isPublicPath(pathname: string): boolean {
  return PUBLIC_PATHS.some((p) => pathname === p || pathname.startsWith(`${p}/`));
}

// Request header carrying the resolved locale to the root layout, which sets
// <html lang>. The root layout sits above app/[lang], so it has no locale param
// of its own and would otherwise have to hard-code one.
const LOCALE_HEADER = "x-locale";

function detectLocale(request: NextRequest): string {
  const acceptLang = request.headers.get("accept-language") ?? "";
  const detected = acceptLang.split(",")[0].split("-")[0].toLowerCase();
  return hasLocale(detected) ? detected : defaultLocale;
}

// The locale already in the path, or the one the Accept-Language header asks for.
function resolveLocale(request: NextRequest): string {
  const { pathname } = request.nextUrl;
  const fromPath = locales.find((l) => pathname === `/${l}` || pathname.startsWith(`/${l}/`));
  return fromPath ?? detectLocale(request);
}

// Continue to the route, telling the root layout which locale to declare.
function passThrough(request: NextRequest): NextResponse {
  const headers = new Headers(request.headers);
  headers.set(LOCALE_HEADER, resolveLocale(request));
  return NextResponse.next({ request: { headers } });
}

// Redirect to the correct locale if not already present in the path.
function redirectToLocale(request: NextRequest): NextResponse | undefined {
  const { pathname } = request.nextUrl;

  // Pass through if locale prefix already present.
  const hasLocalePrefix = locales.some(
    (l) => pathname === `/${l}` || pathname.startsWith(`/${l}/`),
  );
  if (hasLocalePrefix) return;

  request.nextUrl.pathname = `/${detectLocale(request)}${pathname}`;
  return NextResponse.redirect(request.nextUrl);
}

export function proxy(request: NextRequest) {
  const { pathname } = request.nextUrl;

  // Always allow public paths through without auth.
  if (isPublicPath(pathname)) return passThrough(request);

  const token = process.env.SHARE_TOKEN;

  // If SHARE_TOKEN is not set, run in public mode (no auth required).
  if (!token) {
    return redirectToLocale(request) ?? passThrough(request);
  }

  // If ?token= query param is present and valid, set auth cookie and redirect without the param.
  // This allows sharing a plain URL like https://example.com/?token=xxx.
  const queryToken = request.nextUrl.searchParams.get("token");
  if (queryToken !== null) {
    if (verifyToken(queryToken, token)) {
      const url = new URL(request.url);
      url.searchParams.delete("token");
      const response = NextResponse.redirect(url);
      response.cookies.set(COOKIE_NAME, cookieValue(token), {
        httpOnly: true,
        sameSite: "lax",
        secure: process.env.NODE_ENV === "production",
        path: "/",
        maxAge: 60 * 60 * 24 * 30, // 30 days
      });
      return response;
    }
    // Invalid token in query param — deny access.
    return NextResponse.redirect(new URL("/unauthorized", request.url));
  }

  // Check auth cookie for subsequent requests.
  const cookie = request.cookies.get(COOKIE_NAME);
  if (cookie?.value && verifyCookie(cookie.value, token)) {
    return redirectToLocale(request) ?? passThrough(request);
  }

  // No valid auth — redirect to unauthorized page.
  return NextResponse.redirect(new URL("/unauthorized", request.url));
}

/**
 * Run the proxy on every page route, excluding only framework internals and named static assets.
 *
 * Dotted paths are intentionally not excluded:
 * repository names can contain dots (e.g. `next.js`),
 * so a blanket `.*\..*` rule would let those repo pages bypass the share-token check.
 *
 * `robots.txt` and `sitemap.xml` are generated by app/robots.ts and app/sitemap.ts,
 * and are excluded so crawlers can read them without being redirected.
 * When adding more of those, or any file to `public/` (e.g. og images),
 * list them here — otherwise they hit the auth gate and locale redirect.
 */
export const config = {
  matcher: ["/((?!_next/static|_next/image|api|favicon.ico|icon.svg|robots.txt|sitemap.xml).*)"],
};
